# Generated by Django 4.2.2 on 2023-06-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoDeLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField()),
                ('capitulos', models.ManyToManyField(blank=True, to='biblia.capitulo')),
                ('livros', models.ManyToManyField(blank=True, to='biblia.livro')),
                ('versiculos', models.ManyToManyField(blank=True, to='biblia.versiculo')),
            ],
        ),
    ]
