# Generated by Django 4.2.2 on 2023-06-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblia', '0002_planodeleitura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='capitulos',
        ),
        migrations.RemoveField(
            model_name='planodeleitura',
            name='capitulos',
        ),
        migrations.RemoveField(
            model_name='planodeleitura',
            name='versiculos',
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade_capitulos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Capitulo',
        ),
        migrations.DeleteModel(
            name='Versiculo',
        ),
    ]
