# Generated by Django 4.2.2 on 2023-06-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblia', '0003_remove_livro_capitulos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planodeleitura',
            name='quandidade_capitulos_por_dia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
