# Generated by Django 4.2.2 on 2023-06-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblia', '0005_listadeleitura'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ordem',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
